./Execute   --Output Paper20240731/PPDataxPPData_2Inf_Reco.root   --Signal Input/PPData_Reco.root  --CheckZ 1  --DoZReweight  0  --SelfMixing   1  --Background   None  --CheckBackgroundZ   0  --CheckSignalHiBin   0  --CheckBackgroundHiBin   0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin  0  --SignalHFShiftFile  None  --HFShiftFile None  --IsPP   1  --IsReco 1  --Fraction  1  --OverSample   1  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/PbPbDataxPbPbData_Centrality030_2Inf_Reco.root   --Signal Input/PbPbData_Reco.root   --CheckZ 1  --DoZReweight  0  --SelfMixing   1  --Background   None  --CheckBackgroundZ   0  --CheckSignalHiBin 1  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  60 --AlternateHiBin  0  --SignalHFShiftFile None  --HFShiftFile  None  --IsPP   0  --IsReco 1  --Fraction  1  --OverSample   1  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/PbPbDataxMinBiasData_Centrality030_2Inf_Reco.root   --Signal Input/PbPbData_Reco.root   --CheckZ 1  --DoZReweight  0  --SelfMixing   0  --Background   Input/MinBiasData2Inf_Reco1.root --CheckBackgroundZ 0  --CheckSignalHiBin   1  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  60 --AlternateHiBin 0  --SignalHFShiftFile  None  --HFShiftFile  SumHF/DataWeight_Centrality030.root --IsPP   0  --IsReco 1  --Fraction  1  --OverSample   200   --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/MinBiasDataxMinBiasData_Centrality030_2Inf_Reco.root   --Signal Input/MinBiasData2Inf_Reco1.root  --CheckZ 0  --DoZReweight  0  --SelfMixing   1  --Background   None  --CheckBackgroundZ   0   --CheckSignalHiBin   0  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin 0  --SignalHFShiftFile  SumHF/DataWeight_Centrality030.root --HFShiftFile  None  --IsPP   0  --IsReco 1  --Fraction  1  --OverSample   1  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/MinBiasDataxMinBiasData_Centrality030_2Inf_Reco_Different1.root --Signal Input/MinBiasData2Inf_Reco1.root  --CheckZ 0  --DoZReweight  0  --SelfMixing   0  --Background   Input/MinBiasData2Inf_Reco2.root   --CheckBackgroundZ   0  --CheckSignalHiBin   0  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin  0  --SignalHFShiftFile  SumHF/DataWeight_Centrality030.root --HFShiftFile  SumHF/DataWeight_Centrality030.root  --IsPP   0  --IsReco 1  --Fraction  1  --OverSample   5  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/MinBiasDataxMinBiasData_Centrality030_2Inf_Reco_Different2.root --Signal Input/MinBiasData2Inf_Reco2.root  --CheckZ 0  --DoZReweight  0  --SelfMixing   0  --Background   Input/MinBiasData2Inf_Reco1.root   --CheckBackgroundZ   0  --CheckSignalHiBin   0  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin  0  --SignalHFShiftFile  SumHF/DataWeight_Centrality030.root --HFShiftFile  SumHF/DataWeight_Centrality030.root  --IsPP   0  --IsReco 1  --Fraction  1  --OverSample   5  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/PbPbDataxPbPbData_Centrality3050_2Inf_Reco.root  --Signal Input/PbPbData_Reco.root   --CheckZ 1  --DoZReweight  0  --SelfMixing   1  --Background   None  --CheckBackgroundZ   0  --CheckSignalHiBin 1  --CheckBackgroundHiBin  0  --HiBinMin  60 --HiBinMax  100   --AlternateHiBin  0  --SignalHFShiftFile None  --HFShiftFile  None  --IsPP   0  --IsReco 1  --Fraction  1  --OverSample   1  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/PbPbDataxMinBiasData_Centrality3050_2Inf_Reco.root  --Signal Input/PbPbData_Reco.root   --CheckZ 1  --DoZReweight  0  --SelfMixing   0  --Background   Input/MinBiasData2Inf_Reco1.root --CheckBackgroundZ 0  --CheckSignalHiBin   1  --CheckBackgroundHiBin  0  --HiBinMin  60 --HiBinMax  100   --AlternateHiBin 0  --SignalHFShiftFile  None  --HFShiftFile  SumHF/DataWeight_Centrality3050.root   --IsPP   0  --IsReco 1  --Fraction  1  --OverSample   200   --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/MinBiasDataxMinBiasData_Centrality3050_2Inf_Reco.root  --Signal Input/MinBiasData2Inf_Reco1.root  --CheckZ 0  --DoZReweight  0  --SelfMixing   1  --Background   None  --CheckBackgroundZ   0   --CheckSignalHiBin   0  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin 0  --SignalHFShiftFile  SumHF/DataWeight_Centrality3050.root   --HFShiftFile  None  --IsPP   0  --IsReco 1  --Fraction  1  --OverSample   1  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/MinBiasDataxMinBiasData_Centrality3050_2Inf_Reco_Different1.root   --Signal Input/MinBiasData2Inf_Reco1.root  --CheckZ 0  --DoZReweight  0  --SelfMixing   0  --Background   Input/MinBiasData2Inf_Reco2.root   --CheckBackgroundZ   0  --CheckSignalHiBin   0  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin  0  --SignalHFShiftFile  SumHF/DataWeight_Centrality3050.root   --HFShiftFile  SumHF/DataWeight_Centrality3050.root   --IsPP   0  --IsReco 1  --Fraction  1  --OverSample   5  --MinPT  2   --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/MinBiasDataxMinBiasData_Centrality3050_2Inf_Reco_Different2.root   --Signal Input/MinBiasData2Inf_Reco2.root  --CheckZ 0  --DoZReweight  0  --SelfMixing   0  --Background   Input/MinBiasData2Inf_Reco1.root   --CheckBackgroundZ   0  --CheckSignalHiBin   0  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin  0  --SignalHFShiftFile  SumHF/DataWeight_Centrality3050.root   --HFShiftFile  SumHF/DataWeight_Centrality3050.root   --IsPP   0  --IsReco 1  --Fraction  1  --OverSample   5  --MinPT  2   --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/PbPbDataxPbPbData_Centrality5090_2Inf_Reco.root --Signal Input/PbPbData_Reco.root   --CheckZ 1  --DoZReweight  0  --SelfMixing   1  --Background   None  --CheckBackgroundZ   0  --CheckSignalHiBin 1  --CheckBackgroundHiBin  0  --HiBinMin  100   --HiBinMax  180   --AlternateHiBin  0  --SignalHFShiftFile None  --HFShiftFile  None  --IsPP   0  --IsReco 1  --Fraction  1  --OverSample   1  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/PbPbDataxMinBiasData_Centrality5090_2Inf_Reco.root --Signal Input/PbPbData_Reco.root   --CheckZ 1  --DoZReweight  0  --SelfMixing   0  --Background   Input/MinBiasData2Inf_Reco1.root --CheckBackgroundZ 0  --CheckSignalHiBin   1  --CheckBackgroundHiBin  0  --HiBinMin  100   --HiBinMax  180   --AlternateHiBin 0  --SignalHFShiftFile  None  --HFShiftFile  SumHF/DataWeight_Centrality5090.root  --IsPP   0  --IsReco 1  --Fraction  1  --OverSample   200   --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/MinBiasDataxMinBiasData_Centrality5090_2Inf_Reco.root --Signal Input/MinBiasData2Inf_Reco1.root  --CheckZ 0  --DoZReweight  0  --SelfMixing   1  --Background   None  --CheckBackgroundZ   0   --CheckSignalHiBin   0  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin 0  --SignalHFShiftFile  SumHF/DataWeight_Centrality5090.root  --HFShiftFile  None  --IsPP   0  --IsReco 1  --Fraction  1  --OverSample   1  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/MinBiasDataxMinBiasData_Centrality5090_2Inf_Reco_Different1.root  --Signal Input/MinBiasData2Inf_Reco1.root  --CheckZ 0  --DoZReweight  0  --SelfMixing   0  --Background   Input/MinBiasData2Inf_Reco2.root   --CheckBackgroundZ   0  --CheckSignalHiBin   0  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin  0  --SignalHFShiftFile  SumHF/DataWeight_Centrality5090.root  --HFShiftFile  SumHF/DataWeight_Centrality5090.root  --IsPP   0  --IsReco 1  --Fraction  1  --OverSample   5  --MinPT  2   --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/MinBiasDataxMinBiasData_Centrality5090_2Inf_Reco_Different2.root  --Signal Input/MinBiasData2Inf_Reco2.root  --CheckZ 0  --DoZReweight  0  --SelfMixing   0  --Background   Input/MinBiasData2Inf_Reco1.root   --CheckBackgroundZ   0  --CheckSignalHiBin   0  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin  0  --SignalHFShiftFile  SumHF/DataWeight_Centrality5090.root  --HFShiftFile  SumHF/DataWeight_Centrality5090.root  --IsPP   0  --IsReco 1  --Fraction  1  --OverSample   5  --MinPT  2   --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &

wait

bash Merge.sh
