./Execute   --Output Paper20240731/DYLLS0xDYLLS0_2Inf.root  --Signal Input/DYLLMC_Gen.root   --CheckZ 1  --DoZReweight  0  --SelfMixing   1  --Background   None  --CheckBackgroundZ   0  --CheckSignalHiBin   0  --CheckBackgroundHiBin   0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin  0  --SignalHFShiftFile  None  --HFShiftFile None  --IsPP   0  --IsReco 0  --Fraction  1  --OverSample   1  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  0,0   --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/DYLLxDYLL_Centrality030_2Inf.root --Signal Input/DYLLMC_Gen.root   --CheckZ 1  --DoZReweight  0  --SelfMixing   1  --Background   None  --CheckBackgroundZ   0  --CheckSignalHiBin   1  --CheckBackgroundHiBin   0  --HiBinMin  0  --HiBinMax  60 --AlternateHiBin  0  --SignalHFShiftFile  None  --HFShiftFile None  --IsPP   0  --IsReco 0  --Fraction  1  --OverSample   1  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/DYLLxHydjet_Centrality030_2Inf.root  --Signal Input/DYLLMC_Gen.root   --CheckZ 1  --DoZReweight   0  --SelfMixing   0  --Background   Input/MinBiasMC_Gen.root   --CheckBackgroundZ   0  --CheckSignalHiBin 1  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  60 --AlternateHiBin  0  --SignalHFShiftFile None  --HFShiftFile  SumHF/GenWeight_Centrality030.root  --IsPP   0  --IsReco 0  --Fraction  1  --OverSample   5  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/DYLLxDYLLS0_Centrality030_2Inf.root  --Signal Input/DYLLMC_Gen1.root  --CheckZ 1  --DoZReweight   0  --SelfMixing   0  --Background   Input/DYLLMC_Gen2.root  --CheckBackgroundZ   1  --CheckSignalHiBin 1  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  60 --AlternateHiBin  0  --SignalHFShiftFile None  --HFShiftFile  None  --IsPP   0  --IsReco 0  --Fraction  1  --OverSample   5  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,0  --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/HydjetxHydjet_Centrality030_2Inf.root   --Signal Input/MinBiasMC_Gen.root   --CheckZ 0  --DoZReweight  0  --SelfMixing   1  --Background   None  --CheckBackgroundZ   0  --CheckSignalHiBin   0  --CheckBackgroundHiBin 0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin  0  --SignalHFShiftFile  SumHF/GenWeight_Centrality030.root  --HFShiftFile  None  --IsPP   0  --IsReco 0  --Fraction  1  --OverSample   1  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/HydjetxHydjet_Centrality030_2Inf_Different1.root --Signal Input/MinBiasMC_Gen1.root   --CheckZ 0  --DoZReweight  0  --SelfMixing   0  --Background   Input/MinBiasMC_Gen2.root  --CheckBackgroundZ   0   --CheckSignalHiBin   0  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin 0  --SignalHFShiftFile  SumHF/GenWeight_Centrality030.root  --HFShiftFile  SumHF/GenWeight_Centrality030.root   --IsPP   0  --IsReco 0  --Fraction  1  --OverSample   5  --MinPT  2  --MaxPT  -1 --MinZPT  40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/HydjetxHydjet_Centrality030_2Inf_Different2.root --Signal Input/MinBiasMC_Gen2.root   --CheckZ 0  --DoZReweight  0  --SelfMixing   0  --Background   Input/MinBiasMC_Gen1.root  --CheckBackgroundZ   0   --CheckSignalHiBin   0  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin 0  --SignalHFShiftFile  SumHF/GenWeight_Centrality030.root  --HFShiftFile  SumHF/GenWeight_Centrality030.root   --IsPP   0  --IsReco 0  --Fraction  1  --OverSample   5  --MinPT  2  --MaxPT  -1 --MinZPT  40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/DYLLxDYLL_Centrality3050_2Inf.root   --Signal Input/DYLLMC_Gen.root   --CheckZ 1  --DoZReweight   0  --SelfMixing   1  --Background   None  --CheckBackgroundZ   0  --CheckSignalHiBin   1  --CheckBackgroundHiBin   0  --HiBinMin  60 --HiBinMax  100   --AlternateHiBin  0  --SignalHFShiftFile  None  --HFShiftFile None  --IsPP   0  --IsReco 0  --Fraction  1  --OverSample   1  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/DYLLxHydjet_Centrality3050_2Inf.root --Signal Input/DYLLMC_Gen.root   --CheckZ 1  --DoZReweight   0  --SelfMixing   0  --Background   Input/MinBiasMC_Gen.root   --CheckBackgroundZ   0  --CheckSignalHiBin 1  --CheckBackgroundHiBin  0  --HiBinMin  60 --HiBinMax  100   --AlternateHiBin  0  --SignalHFShiftFile None  --HFShiftFile  SumHF/GenWeight_Centrality3050.root --IsPP   0  --IsReco 0  --Fraction  1  --OverSample   5  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/DYLLxDYLLS0_Centrality3050_2Inf.root --Signal Input/DYLLMC_Gen1.root  --CheckZ 1  --DoZReweight   0  --SelfMixing   0  --Background   Input/DYLLMC_Gen2.root  --CheckBackgroundZ   1  --CheckSignalHiBin 1  --CheckBackgroundHiBin  0  --HiBinMin  60 --HiBinMax  100   --AlternateHiBin  0  --SignalHFShiftFile None  --HFShiftFile  None  --IsPP   0  --IsReco 0  --Fraction  1  --OverSample   5  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,0  --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/HydjetxHydjet_Centrality3050_2Inf.root  --Signal Input/MinBiasMC_Gen.root   --CheckZ 0  --DoZReweight  0  --SelfMixing   1  --Background   None  --CheckBackgroundZ   0  --CheckSignalHiBin   0  --CheckBackgroundHiBin 0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin  0  --SignalHFShiftFile  SumHF/GenWeight_Centrality3050.root --HFShiftFile  None  --IsPP   0  --IsReco 0  --Fraction  1  --OverSample   1  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/HydjetxHydjet_Centrality3050_2Inf_Different1.root   --Signal Input/MinBiasMC_Gen1.root   --CheckZ 0  --DoZReweight  0  --SelfMixing   0  --Background   Input/MinBiasMC_Gen2.root  --CheckBackgroundZ 0  --CheckSignalHiBin   0  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin 0  --SignalHFShiftFile  SumHF/GenWeight_Centrality3050.root --HFShiftFile  SumHF/GenWeight_Centrality3050.root  --IsPP   0  --IsReco 0  --Fraction  1  --OverSample   5  --MinPT  2  --MaxPT  -1 --MinZPT  40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/HydjetxHydjet_Centrality3050_2Inf_Different2.root   --Signal Input/MinBiasMC_Gen2.root   --CheckZ 0  --DoZReweight  0  --SelfMixing   0  --Background   Input/MinBiasMC_Gen1.root  --CheckBackgroundZ 0  --CheckSignalHiBin   0  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin 0  --SignalHFShiftFile  SumHF/GenWeight_Centrality3050.root --HFShiftFile  SumHF/GenWeight_Centrality3050.root  --IsPP   0  --IsReco 0  --Fraction  1  --OverSample   5  --MinPT  2  --MaxPT  -1 --MinZPT  40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/DYLLxDYLL_Centrality5090_2Inf.root   --Signal Input/DYLLMC_Gen.root   --CheckZ 1  --DoZReweight   0  --SelfMixing   1  --Background   None  --CheckBackgroundZ   0  --CheckSignalHiBin   1  --CheckBackgroundHiBin   0  --HiBinMin  100   --HiBinMax  180   --AlternateHiBin  0  --SignalHFShiftFile  None  --HFShiftFile None  --IsPP   0  --IsReco 0  --Fraction  1  --OverSample   1  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/DYLLxHydjet_Centrality5090_2Inf.root --Signal Input/DYLLMC_Gen.root   --CheckZ 1  --DoZReweight   0  --SelfMixing   0  --Background   Input/MinBiasMC_Gen.root   --CheckBackgroundZ   0  --CheckSignalHiBin 1  --CheckBackgroundHiBin  0  --HiBinMin  100   --HiBinMax  180   --AlternateHiBin  0  --SignalHFShiftFile None  --HFShiftFile  SumHF/GenWeight_Centrality5090.root --IsPP   0  --IsReco 0  --Fraction  1  --OverSample   5  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/DYLLxDYLLS0_Centrality5090_2Inf.root --Signal Input/DYLLMC_Gen1.root  --CheckZ 1  --DoZReweight   0  --SelfMixing   0  --Background   Input/DYLLMC_Gen2.root  --CheckBackgroundZ   1  --CheckSignalHiBin 1  --CheckBackgroundHiBin  0  --HiBinMin  100   --HiBinMax  180   --AlternateHiBin  0  --SignalHFShiftFile None  --HFShiftFile  None  --IsPP   0  --IsReco 0  --Fraction  1  --OverSample   5  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,0  --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/HydjetxHydjet_Centrality5090_2Inf.root  --Signal Input/MinBiasMC_Gen.root   --CheckZ 0  --DoZReweight  0  --SelfMixing   1  --Background   None  --CheckBackgroundZ   0  --CheckSignalHiBin   0  --CheckBackgroundHiBin 0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin  0  --SignalHFShiftFile  SumHF/GenWeight_Centrality5090.root --HFShiftFile  None  --IsPP   0  --IsReco 0  --Fraction  1  --OverSample   1  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/HydjetxHydjet_Centrality5090_2Inf_Different1.root   --Signal Input/MinBiasMC_Gen1.root   --CheckZ 0  --DoZReweight  0  --SelfMixing   0  --Background   Input/MinBiasMC_Gen2.root  --CheckBackgroundZ 0  --CheckSignalHiBin   0  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin 0  --SignalHFShiftFile  SumHF/GenWeight_Centrality5090.root --HFShiftFile  SumHF/GenWeight_Centrality5090.root  --IsPP   0  --IsReco 0  --Fraction  1  --OverSample   5  --MinPT  2  --MaxPT  -1 --MinZPT  40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/HydjetxHydjet_Centrality5090_2Inf_Different2.root   --Signal Input/MinBiasMC_Gen2.root   --CheckZ 0  --DoZReweight  0  --SelfMixing   0  --Background   Input/MinBiasMC_Gen1.root  --CheckBackgroundZ 0  --CheckSignalHiBin   0  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin 0  --SignalHFShiftFile  SumHF/GenWeight_Centrality5090.root --HFShiftFile  SumHF/GenWeight_Centrality5090.root  --IsPP   0  --IsReco 0  --Fraction  1  --OverSample   5  --MinPT  2  --MaxPT  -1 --MinZPT  40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &

wait

bash Merge.sh
