./Execute   --Output Paper20240731/PPMCxPPMC_2Inf_Reco.root --Signal Input/PPMC_Reco.root --CheckZ 1  --DoZReweight  0  --SelfMixing   1  --Background   None  --CheckBackgroundZ   0  --CheckSignalHiBin   0  --CheckBackgroundHiBin   0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin  0  --SignalHFShiftFile  None  --HFShiftFile None  --IsPP   1  --IsReco 1  --Fraction  1  --OverSample   1  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/DYLLxDYLL_Centrality030_2Inf_Reco.root  --Signal Input/DYLLMC_Reco.root  --CheckZ 1  --DoZReweight  0  --SelfMixing   1  --Background   None  --CheckBackgroundZ   0  --CheckSignalHiBin   1  --CheckBackgroundHiBin 0  --HiBinMin  0  --HiBinMax  60 --AlternateHiBin  0  --SignalHFShiftFile  None  --HFShiftFile None  --IsPP   0  --IsReco 1  --Fraction  1  --OverSample   1  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/DYLLxHydjet_Centrality030_2Inf_Reco.root   --Signal Input/DYLLMC_Reco.root  --CheckZ 1  --DoZReweight  0  --SelfMixing   0  --Background   Input/MinBiasMC_Reco.root  --CheckBackgroundZ   0  --CheckSignalHiBin 1  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  60 --AlternateHiBin  0  --SignalHFShiftFile None  --HFShiftFile  SumHF/RecoWeight_Centrality030.root --IsPP   0  --IsReco 1  --Fraction  1  --OverSample   25 --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/HydjetxHydjet_Centrality030_2Inf_Reco.root --Signal Input/MinBiasMC_Reco.root  --CheckZ 0  --DoZReweight  0  --SelfMixing   1  --Background   None  --CheckBackgroundZ   0  --CheckSignalHiBin   0  --CheckBackgroundHiBin 0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin  0  --SignalHFShiftFile  SumHF/RecoWeight_Centrality030.root --HFShiftFile  None  --IsPP   0  --IsReco 1  --Fraction  1  --OverSample   1  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/HydjetxHydjet_Centrality030_2Inf_Reco_Different1.root  --Signal Input/MinBiasMC_Reco1.root  --CheckZ 0  --DoZReweight  0  --SelfMixing   0  --Background   Input/MinBiasMC_Reco2.root --CheckBackgroundZ 0  --CheckSignalHiBin   0  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin 0  --SignalHFShiftFile  SumHF/RecoWeight_Centrality030.root --HFShiftFile  SumHF/RecoWeight_Centrality030.root  --IsPP   0  --IsReco 1  --Fraction  1  --OverSample   25 --MinPT  2  --MaxPT  -1 --MinZPT  40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/HydjetxHydjet_Centrality030_2Inf_Reco_Different2.root  --Signal Input/MinBiasMC_Reco2.root  --CheckZ 0  --DoZReweight  0  --SelfMixing   0  --Background   Input/MinBiasMC_Reco1.root --CheckBackgroundZ 0  --CheckSignalHiBin   0  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin 0  --SignalHFShiftFile  SumHF/RecoWeight_Centrality030.root --HFShiftFile  SumHF/RecoWeight_Centrality030.root  --IsPP   0  --IsReco 1  --Fraction  1  --OverSample   25 --MinPT  2  --MaxPT  -1 --MinZPT  40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/DYLLxDYLL_Centrality3050_2Inf_Reco.root --Signal Input/DYLLMC_Reco.root  --CheckZ 1  --DoZReweight  0  --SelfMixing   1  --Background   None  --CheckBackgroundZ   0  --CheckSignalHiBin   1  --CheckBackgroundHiBin 0  --HiBinMin  60 --HiBinMax  100   --AlternateHiBin  0  --SignalHFShiftFile  None  --HFShiftFile None  --IsPP   0  --IsReco 1  --Fraction  1  --OverSample   1  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/DYLLxHydjet_Centrality3050_2Inf_Reco.root  --Signal Input/DYLLMC_Reco.root  --CheckZ 1  --DoZReweight  0  --SelfMixing   0  --Background   Input/MinBiasMC_Reco.root  --CheckBackgroundZ   0  --CheckSignalHiBin 1  --CheckBackgroundHiBin  0  --HiBinMin  60 --HiBinMax  100   --AlternateHiBin  0  --SignalHFShiftFile None  --HFShiftFile  SumHF/RecoWeight_Centrality3050.root   --IsPP   0  --IsReco 1  --Fraction  1  --OverSample 25 --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/HydjetxHydjet_Centrality3050_2Inf_Reco.root   --Signal Input/MinBiasMC_Reco.root  --CheckZ  0  --DoZReweight  0  --SelfMixing   1  --Background   None  --CheckBackgroundZ   0  --CheckSignalHiBin 0  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin  0  --SignalHFShiftFile SumHF/RecoWeight_Centrality3050.root   --HFShiftFile  None  --IsPP   0  --IsReco 1  --Fraction  1  --OverSample 1  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/HydjetxHydjet_Centrality3050_2Inf_Reco_Different1.root --Signal Input/MinBiasMC_Reco1.root  --CheckZ 0  --DoZReweight  0  --SelfMixing   0  --Background   Input/MinBiasMC_Reco2.root --CheckBackgroundZ 0  --CheckSignalHiBin   0  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin 0  --SignalHFShiftFile  SumHF/RecoWeight_Centrality3050.root   --HFShiftFile  SumHF/RecoWeight_Centrality3050.root --IsPP   0  --IsReco 1  --Fraction  1  --OverSample   25 --MinPT  2  --MaxPT  -1 --MinZPT  40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/HydjetxHydjet_Centrality3050_2Inf_Reco_Different2.root --Signal Input/MinBiasMC_Reco2.root  --CheckZ 0  --DoZReweight  0  --SelfMixing   0  --Background   Input/MinBiasMC_Reco1.root --CheckBackgroundZ 0  --CheckSignalHiBin   0  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin 0  --SignalHFShiftFile  SumHF/RecoWeight_Centrality3050.root   --HFShiftFile  SumHF/RecoWeight_Centrality3050.root --IsPP   0  --IsReco 1  --Fraction  1  --OverSample   25 --MinPT  2  --MaxPT  -1 --MinZPT  40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/DYLLxDYLL_Centrality5090_2Inf_Reco.root --Signal Input/DYLLMC_Reco.root  --CheckZ 1  --DoZReweight  0  --SelfMixing   1  --Background   None  --CheckBackgroundZ   0  --CheckSignalHiBin   1  --CheckBackgroundHiBin 0  --HiBinMin  100   --HiBinMax  180   --AlternateHiBin  0  --SignalHFShiftFile  None  --HFShiftFile None  --IsPP   0  --IsReco 1  --Fraction  1  --OverSample   1  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/DYLLxHydjet_Centrality5090_2Inf_Reco.root  --Signal Input/DYLLMC_Reco.root  --CheckZ 1  --DoZReweight  0  --SelfMixing   0  --Background   Input/MinBiasMC_Reco.root  --CheckBackgroundZ   0  --CheckSignalHiBin 1  --CheckBackgroundHiBin  0  --HiBinMin  100   --HiBinMax  180   --AlternateHiBin  0  --SignalHFShiftFile None  --HFShiftFile  SumHF/RecoWeight_Centrality5090.root   --IsPP   0  --IsReco 1  --Fraction  1  --OverSample 25 --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/HydjetxHydjet_Centrality5090_2Inf_Reco.root   --Signal Input/MinBiasMC_Reco.root  --CheckZ  0  --DoZReweight  0  --SelfMixing   1  --Background   None  --CheckBackgroundZ   0  --CheckSignalHiBin 0  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin  0  --SignalHFShiftFile SumHF/RecoWeight_Centrality5090.root   --HFShiftFile  None  --IsPP   0  --IsReco 1  --Fraction  1  --OverSample 1  --MinPT  2  --MaxPT  -1 --MinZPT 40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/HydjetxHydjet_Centrality5090_2Inf_Reco_Different1.root --Signal Input/MinBiasMC_Reco1.root  --CheckZ 0  --DoZReweight  0  --SelfMixing   0  --Background   Input/MinBiasMC_Reco2.root --CheckBackgroundZ 0  --CheckSignalHiBin   0  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin 0  --SignalHFShiftFile  SumHF/RecoWeight_Centrality5090.root   --HFShiftFile  SumHF/RecoWeight_Centrality5090.root --IsPP   0  --IsReco 1  --Fraction  1  --OverSample   25 --MinPT  2  --MaxPT  -1 --MinZPT  40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &
./Execute   --Output Paper20240731/HydjetxHydjet_Centrality5090_2Inf_Reco_Different2.root --Signal Input/MinBiasMC_Reco2.root  --CheckZ 0  --DoZReweight  0  --SelfMixing   0  --Background   Input/MinBiasMC_Reco1.root --CheckBackgroundZ 0  --CheckSignalHiBin   0  --CheckBackgroundHiBin  0  --HiBinMin  0  --HiBinMax  200   --AlternateHiBin 0  --SignalHFShiftFile  SumHF/RecoWeight_Centrality5090.root   --HFShiftFile  SumHF/RecoWeight_Centrality5090.root --IsPP   0  --IsReco 1  --Fraction  1  --OverSample   25 --MinPT  2  --MaxPT  -1 --MinZPT  40 --DoDiHadron   1  --SubEvent  -1,-1 --ExtraZ -1 --MaxAbsEta -1 &

wait

bash Merge.sh
